[project]
name = "openday-scavenger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.112.2",
    "jinja2>=3.1.4",
    "sqlalchemy>=2.0.32",
    "segno>=1.6.1",
    "reportlab>=4.2.2",
    "pydantic-settings>=2.4.0",
    "python-dotenv>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"
